{% set name = "google-auth" %}
{% set version = "2.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}-library-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7e53bdb219759a67ab6a46dc8bd0d860f84ba2172fe6b82b91478776aca6b01f

build:
  number: 1
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - patch    # [unix]
    - m2-patch # [win]
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - cachetools >=2.0.0,<6.0
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<5
    # extras: keep them in run to avoid breaking environments
    - aiohttp >=3.6.2,<4.0.0.dev0
    - requests >=2.20.0,<3.0.0.dev0
    - pyopenssl >=20.0.0
  run_constrained:
    - cryptography >=38.0.3
    # 2023/9/7: pyu2f isn't available on defaults yet
    - pyu2f >=0.1.5
    - pyjwt >=2.0

#aioresponses =* * does not exist (perhaps a typo or a missing channel);
{% set ignore_tests = " --ignore=tests/transport/aio/test_sessions.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/transport/aio/test_aiohttp.py" %}
{% set ignore_tests_async = " --ignore=tests_async/transport/test_aiohttp_requests.py" %}

#pyu2f =* * does not exist (perhaps a typo or a missing channel).
{% set ignore_tests = ignore_tests + " --ignore=tests/oauth2/test_challenges.py" %}

# ctypes.ArgumentError: argument 2: TypeError: expected LP_c_ulonglong instance instead of pointer to c_ulong
{% set tests_to_skip = "test_get_config_path_unix" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_config_path_no_appdata" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_auth_access_token_with_account" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_load_credentials_from_file_external_account_bad_format" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_load_credentials_from_file_external_account_authorized_user_bad_format" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_default_environ_external_credentials_bad_format" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_retrieve_subject_token_json_file_invalid_field_name" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_retrieve_subject_token_invalid_json" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_refresh_with_retrieve_subject_token_error" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_sign_callback" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_sign_callback_failed_to_sign" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test__run_subprocess_ignore_stderr" %}  # [win]

# 'google-auth 2.38.0' `tests/transport/test__mtls_helper.py` failed with the `AttributeError: module 'OpenSSL.crypto' has no attribute 'sign'`. 
# See also the upstream issue  https://github.com/googleapis/google-auth-library-python/issues/1665,
# because because pyopenssl >=24.3.0 removed the `OpenSSL.crypto.sign` function, see https://github.com/googleapis/google-auth-library-python/issues/1665
{% set tests_to_skip = tests_to_skip + " or test__mtls_helper" %}

test:
  source_files:
    - tests
    - tests_async
  imports:
    - google.auth
  commands:
    - python -m pip check

    - pytest -v {{ ignore_tests }} tests                                 # [not win]
    - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" tests  # [win]

    - pytest -v {{ ignore_tests_async }} tests_async
  requires:
    - pip
    - pytest
    - pytest-localserver
    - mock
    - responses
    - flask
    - freezegun
    - flask
    - pyjwt >=2.0
  downstreams:
    - google-cloud-storage

about:
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: |
    This library provides the ability to authenticate to Google APIs using various methods.
    It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io
  dev_url: https://github.com/googleapis/google-auth-library-python

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
