{% set name = "google-auth" %}
{% set version = "2.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/{{ name }}-library-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7e53bdb219759a67ab6a46dc8bd0d860f84ba2172fe6b82b91478776aca6b01f

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - cachetools >=2.0.0,<6.0
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<5
    # extras: keep them in run to avoid breaking environments
    - aiohttp >=3.6.2,<4.0.0dev
    - requests >=2.20.0,<3.0.0.dev
    - pyopenssl >=20.0.0
  run_constrained:
    - cryptography >=38.0.3
    # 2023/9/7: pyu2f isn't available on defaults yet
    - pyu2f >=0.1.5
    - pyjwt >=2.0
    - cryptography >=38.0.3

#aioresponses =* * does not exist (perhaps a typo or a missing channel);
{% set ignore_tests = " --ignore=tests/transport/aio/test_sessions.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/transport/aio/test_aiohttp.py" %}
{% set ignore_tests_async = " --ignore=tests_async/transport/test_aiohttp_requests.py" %}

#pyu2f =* * does not exist (perhaps a typo or a missing channel).
{% set ignore_tests = ignore_tests + " --ignore=tests/oauth2/test_challenges.py" %}

test:
  source_files:
    - tests
    - tests_async
  imports:
    - google.auth
  commands:
    - python -m pip check
    - pytest -v {{ ignore_tests }} tests
    - pytest -v {{ ignore_tests_async }} tests_async
  requires:
    - pip
    - pytest
    - pytest-localserver
    - mock
    - responses
    - flask
    - freezegun
    - flask
    - pyjwt >=2.0
  downstreams:
    - google-cloud-storage

about:
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: |
    This library provides the ability to authenticate to Google APIs using various methods.
    It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io
  dev_url: https://github.com/googleapis/google-auth-library-python

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
