{% set name = "google-auth" %}
{% set version = "2.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: f90fa030b569a92654b9d690665a073841df33d57487be53db583a9a0867a553

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - pyasn1-modules >=0.2.1
    - cryptography >=38.0.3  # [py<314]
    - cryptography >=41.0.5  # [py>=314]
    - rsa >=4.0.0,<5
    # extras: keep them in run to avoid breaking environments
    - aiohttp >=3.8.0,<4.0.0  # [py<314]
    - aiohttp >=3.9.0,<4.0.0  # [py>=314]
    - requests >=2.30.0,<3.0.0
  run_constrained:
    # 2026/1/20: pyu2f isn't available on defaults yet
    - pyu2f >=0.1.5
    - pyjwt >=2.0

#aioresponses =* * does not exist (perhaps a typo or a missing channel);
{% set ignore_tests = " --ignore=tests/transport/aio" %}

#pyu2f =* * does not exist (perhaps a typo or a missing channel).
{% set ignore_tests = ignore_tests + " --ignore=tests/oauth2/test_challenges.py" %}

{% set tests_to_skip = "" %}
# ctypes.ArgumentError: argument 2: TypeError: expected LP_c_ulonglong instance instead of pointer to c_ulong
{% set tests_to_skip = "test_get_config_path_unix" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_config_path_no_appdata" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_auth_access_token_with_account" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_load_credentials_from_file_external_account_bad_format" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_load_credentials_from_file_external_account_authorized_user_bad_format" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_default_environ_external_credentials_bad_format" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_retrieve_subject_token_json_file_invalid_field_name" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_retrieve_subject_token_invalid_json" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_refresh_with_retrieve_subject_token_error" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_sign_callback" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_get_sign_callback_failed_to_sign" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test__run_subprocess_ignore_stderr" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test__MdsMtlsConfig_windows_defaults" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test__MdsMtlsConfig_non_windows_defaults" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or negative_timestamp" %}  # [win]

test:
  source_files:
    - tests
  imports:
    - google.auth
    - google.oauth2
  commands:
    - python -m pip check

    - pytest -v {{ ignore_tests }} tests                                 # [not win]
    - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" tests  # [win]
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-localserver
    - mock
    - responses
    - flask
    - freezegun
    - flask
    - pyjwt >=2.0
  downstreams:
    - google-cloud-storage

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-auth
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: |
    This library provides the ability to authenticate to Google APIs using various methods.
    It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-auth

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
