{% set name = "google-auth" %}
{% set version = "1.6.2" %}
{% set sha256 = "e8d64e9bc8cb6f0fc5360c693f86dc9ee6964081ee702e3b5ddc937f99efc950" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<4dev
    - six >=1.9.0,<2dev
    - cachetools >=2.0.0,<3dev

test:
  imports:
    - google.auth

about:
  home: https://github.com/GoogleCloudPlatform/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Google authentication library for Python'
  description: This library provides the ability to authenticate to Google APIs using various
    methods. It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io/en/latest/
  dev_url: https://github.com/GoogleCloudPlatform/google-auth-library-python

extra:
  recipe-maintainers:
    - parthea
    - jreback
    - tswast
    - theacodes
