{% set name = "google-auth" %}
{% set version = "2.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 164cba9af4e6e4e40c3a4f90a1a6c12ee56f14c0b4868d1ca91b32826ab334ce

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - cachetools >=2.0.0,<6.0
    - pyasn1-modules >=0.2.1
    - rsa >=3.1.4,<5
    - six >=1.9.0
    - urllib3 <2.0
    # extras: keep them in run to avoid breaking environments
    - aiohttp >=3.6.2,<4.0.0dev
    - requests >=2.20.0,<3.0.0dev
    - pyopenssl >=20.0.0
  run_constrained:
    - cryptography >=38.0.3
    # 2023/9/7: pyu2f isn't available on defaults yet
    - pyu2f >=0.1.5

test:
  requires:
    - pip
  imports:
    - google.auth
  commands:
    - python -m pip check
  downstreams:
    - google-cloud-storage

about:
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
  description: |
    This library provides the ability to authenticate to Google APIs using various methods. 
    It also provides integration with several HTTP libraries.
  doc_url: https://google-auth.readthedocs.io/en/latest/
  dev_url: https://github.com/googleapis/google-auth-library-python

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
