travis:
  secure:
    BINSTAR_TOKEN: BT40nfbKNuoH1huJYOjhX2n+eybzZio37oDAMpQ8R+QiDQVnWMjug417wxEKte4BqKAisKxxBhGVVQjOjOMHMtJFlg8Hd9syTqWkT46alur9KVnh8zhzc4+E51zs/NE/2QkTvvFfl8AbMtT3hWWEI7WeJv2+KSwWApS03R0l73ut4FA1Npxu1E9jAKtBpZdoMaCdm2TDwGiLLRExyU7319pTElmkFjQD1M8mOw1oSGWhzms/hjF0s3df+IOkjDd99hr+05Gwe7WNGV+HFBWvl4Vy2t5GVwQ7yCamBzGl81axZZ2s8honLqYuI/t+MHOAvcjyBW6gTiDHveaZoJXixiE9K6WqnNAITi0xEuHFeCA8K1ef/lnyuQPhKt0Y9FIGxX1xejWqNLv7c84Hmu4B37QGshx3cBNa0kNnLwQVt/f3zSvGqgQRYS6CMu02KWCvcgp4d/CkIod3pmUvbmoUPh1zBuxmiDmeZ7c9zQMzfILysjSlrYoS5ayHt5W+2HV4D0z7L0K+dYiPVjHAdSH8XGXCeb46o70Mop/uO2tiAIkm99Xk3iJgXPcagZkgzqvpysr1dXIBZ6MRus8gY/jcngvXRcGLEXdDCI0paILPT341IAFY6rl2y1z9k652274Km4RSf4mfvH6uvCgh4t6otO3CNiEDcF/JkPvV9KzFanE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
