travis:
  secure:
    BINSTAR_TOKEN: co9scMiNRGHTyALCjWI/p4Eb3HRg+O9Nhpq4LdYaHvI4Vtqj9Ql4IP6yK5gjB9lwPwuqbK1FdZDOqMAadCRiaKVeGWZXiTIBnHT3UHRV8K0ci3WPxgcesqL5h9cpBSOkzc9x/yjv7JdTl2KjfCP0ZGxlYrHZ1LUX75X71rz0n9sfGOPz2/XbAED4RA3eIlqMYfYzuiLbTjit/81HyewoCmyNTgSn0GiOKpNIMWng6vnHBA30btsUjfs5l9WH5ZcMaCAix2iRsgYWrOMnR9wHRNMYsRd7aPfmu+GHIVD99Mn9jypyDOkJ+Gz48+2jYOrmGo/yeGj5EThsmA9PzCoGwFKIFT7iIfmJgMFJNXGpNzByzr4H1BGs+sl3uIrRs/7m8WwilB7y7rlKkxZyFLJvE13Z4R8Zd/AwFny7hGKpXXXfobjOy39j35OWiC1owY1j2xwLHZjQSJR1nXAOWSFDKLxiTZjvVEOaaiWIi7rXEmxn9fqgHwMtUAZOW22gUPxFa34kMMtUvmeX4MSxPcFLluuH8HlQdh/jjo1XU46QmiS+BCz0/akfw5xKlg62nOO1ItI7QX2M2q4fH6i49oXGslqKsVdlTVXDpv9sAnX1C+LJ9UAmhap+BiYQguf1zgWaQgI37DbdYcTMqzdosCtHOHMm9n/kX8gMT/HWAr6t9Fg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
